config/routes.rb
Rails.application.routes.draw do
  root 'search#index'

  get 'search/search'

  get 'search/list'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/search.rb
class Search < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @search = Search.new
  end

  def search
    @username = params[:search][:username]
    @github_url = "https://github.com/"+@username

    begin
      get_github_response = RestClient.get @github_url
    rescue RestClient::ExceptionWithResponse => e
      e.response
    end
    test = Search.find_by_username(@username)
    if test 
      test.count +=1
      test.save
    else
      yeni = Search.new
      yeni.username = @username
      yeni.count = 1
      yeni.save
    end

    redirect_to @github_url unless e

  end

  def list
    @all_list = Search.all.order('count DESC')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdeoGithubProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<nav class="navbar navbar-expand-lg navbar-light bg-light">
            <%= link_to "Adeo Github Project", root_path, class: "navbar-brand" %>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <%= link_to "Anasayfa", root_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Tüm Liste", search_list_path, class: "nav-link" %>
                </li>
                </ul>
            </div>
            </nav>
			<%= yield %>
		</div>
	</div>
</div>
    
  </body>
</html>

app/views/search/index.html.erb
<div class="jumbotron">
    <h2>
        Hello, User!
    </h2>
    <p>
        <%= simple_form_for @search, url: search_search_path, method: 'GET' do |f| %>
        <%= f.input :username, label: "Kullanıcı Adı:" %>
        <%= f.button :submit, "Ara", class: "btn btn-primary btn-large" %>
        <% end %>
    </p>
</div>
		

app/views/search/list.html.erb
<h1>All List</h1>
<table class="table table-bordered">
    <thead>
        <th> Username </th>
        <th> Count </th>
    </thead>
    <tbody>
    <% @all_list.each do |object| %>
        <tr>
            <td> <%= object.username %> </td>
            <td> <%= object.count %> </td>
        </tr>
    <% end %>
    </tbody>
</table>

app/views/search/search.html.erb
<div class="jumbotron">
    <h2>
        404 Not Found
    </h2>
    <p>
        Hey adamım, aradığın <%= @username %> kullanıcısını githuba sorduk yogh dedi :D 
    </p>
</div>